name: Build artifacts

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and build artifacts
        uses: actions/checkout@v3
      - name: Build artifacts
        run: sudo bash ${GITHUB_WORKSPACE}/example_generator/run.sh ${GITHUB_WORKSPACE}
      - name: Upload artifact file
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/example_generator/artifacts.txt
